plugins {
    id 'application'
    id 'jacoco'
}

apply from: 'dependencies.gradle'

repositories {
    mavenCentral()
}

configurations.configureEach {
    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

dependencies {
    annotationProcessor libs.lombok

    implementation libs.lombok
    implementation springBootDeps

    implementation loggingDeps

    testImplementation (libs.springbootTest) {
        exclude group: "junit", module: "junit"
    }
    testRuntimeOnly libs.junitplatform
}

test {
    finalizedBy jacocoTestReport
}
jacocoTestReport {
    dependsOn test
}

jacoco {
    toolVersion = "0.8.15"
    reportsDirectory = layout.buildDirectory.dir('customJacocoReportDir')
}